
package gui;

import Tic_Tac_Toe_Game.Human;
import io.DBHandler;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class PlayersFrame extends javax.swing.JFrame {

    private GameFrame game;
    private DBHandler dbHandler;
    private PlayerTableModel tablemodel;
    
    public PlayersFrame() {
        initComponents();
    }

    PlayersFrame(GameFrame game,DBHandler dbHandler,boolean overall) {
        this();
        this.game = game;
        this.dbHandler = dbHandler;
        dbHandler.refresh();
        tablemodel = new PlayerTableModel(dbHandler.getPlayers());
        tblPlayers.setModel(tablemodel);
        txtSearch.setText("Type to search...");
        txtSearch.setVisible(!overall);
        btnDeleteAll.setVisible(!overall);
        btnDeletePlayer.setVisible(!overall);
        tblPlayers.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        btnDeleteAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlayers = new javax.swing.JTable();
        btnDeletePlayer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Player List");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtSearch.setText("Type to search...");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnDeleteAll.setText("Delete All Players");
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        tblPlayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPlayers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblPlayers);

        btnDeletePlayer.setText("Delete Selected Player");
        btnDeletePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePlayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnDeletePlayer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnDeleteAll)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAll)
                    .addComponent(btnDeletePlayer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        game.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete All players?", "Delete All Players", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION){
                new Thread(){
                    public void run() {
                        dbHandler.deletePlayer("");
                        dbHandler.refresh();
                        tablemodel.setPlayers(dbHandler.getPlayers());
                    }
                }.start();
            }
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    private void btnDeletePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePlayerActionPerformed
        if (tblPlayers.getSelectedRow()>=0){
            int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this player?", "Delete Player", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION){
                new Thread(){
                    public void run() {
                        dbHandler.deletePlayer((String) tblPlayers.getValueAt(tblPlayers.getSelectedRow(), 0));
                        dbHandler.refresh();
                        tablemodel.setPlayers(dbHandler.getPlayers());
                    }
                }.start();
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "No player selected!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeletePlayerActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        if (txtSearch.getText().equals("Type to search...")){
            txtSearch.setText("");
        }
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        tablemodel.setSelectedPlayerList(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    public void setUp(){
        dbHandler.refresh();
        tablemodel.setPlayers(dbHandler.getPlayers());
    }
    
    public void setUp(Human player1, Human player2){
        ArrayList<Human> players = new ArrayList<Human>();
        if (player1!=null){
            players.add(player1);
        }
        if (player2!=null){
            players.add(player2);
        }
        tablemodel.setPlayers(players);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnDeletePlayer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPlayers;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
